name: CI
on:
  push:
    branches: [ main, dshao009/imdbParser_scrapeMovies ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: Run tests
      run: |
        cmake .
        make
        ./test
