name: CI
on:
  [ push, pull_request ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: Run tests
      run: |
        sudo apt install libcurl4-gnutls-dev
        git submodule update --init
        cmake .
        make
        ./test
